#define IDB_SQUARE_W       110
#define IDB_SQUARE_B       120
#define IDB_SQUARE_HGHLGHT 130
#define IDB_SQUARE_SELECT  140

#define IDB_CHSMN_PAWN_W   111
#define IDB_CHSMN_ROOK_W   112
#define IDB_CHSMN_KNIGHT_W 113
#define IDB_CHSMN_BISHOP_W 114
#define IDB_CHSMN_QUEEN_W  115
#define IDB_CHSMN_KING_W   116

#define IDB_CHSMN_PAWN_B   121
#define IDB_CHSMN_ROOK_B   122
#define IDB_CHSMN_KNIGHT_B 123
#define IDB_CHSMN_BISHOP_B 124
#define IDB_CHSMN_QUEEN_B  125
#define IDB_CHSMN_KING_B   126
